spring:
  threads:
    virtual:
      enabled: true

langchain4j:
  open-ai:
    client:
      api-key: ${OPENAI_API_KEY}
    chat:
      options:
        model: gpt-3.5-turbo
        temperature: 0.7
